site_name: Spatial Computing Project

nav:
  - Home: "index.md"
  - A1_Planning: 
      - Process: "A1_Planning/Process.md"
      - Product: "A1_Planning/Products.md"
  - A2_Configuring:
      - Process: "A2_Configuring/Process.md"
      - Product: "A2_Configuring/Products.md"
  - A3_Massing:
      - Process: "A3_Massing/Process.md"
      - Product: "A3_Massing/Products.md"
  - A4_Forming: 
      - Process: "A4_Forming/Process.md"
      - Product: "A4_Forming/Products.md"
  - About: "about.md"
  - Index:
      - Scripts: "index/scripts.md"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"
  palette:
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

  font:
    text: Roboto

markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
