site_name: Spatial Computing Project

nav:
  - Home: "index.md"
  - A1_Planning: 
      - Process: "A1_Planning/Process.md"
      - Product: "A1_Planning/Products.md"
  - A2_Configuring:
      - Process: "A2_Configuring/Process.md"
      - Product: "A2_Configuring/Products.md"
  - A3_Massing:
      - Process:
          Atrium Allocation: "A3_Massing/Process/Atrium allocation/Atrium allocation.md" 
          Shadow casting analysis: "A3_Massing/Process/Shadow casting analysis/Shadow analysis.md"
          Visibility analysis: "A3_Massing/Process/Visibility analysis/Visibility analysis.md"        
          Sun access analysis: "A3_Massing/Process/Sun access analysis/Sun analysis.md"
          Public entrance analysis: "A3_Massing/Process/Public entrance analysis/Public entrance analysis.md"
          Green acces analysis: "A3_Massing/Process/Green acces analysis/Green acces analysis.md"
          Noise analysis: "A3_Massing/Process/Noise Analysis/Noise analysis.md"
      - Product: 
          Seed allocation: "A3_Massing/Products/Seed allocation/Seed allocation.md"
          Shortest paths: "A3_Massing/Products/Shortest paths/Shortest paths.md"
          Agent growth: "A3_Massing/Products/Agent growth/Agent growth.md"
  - A4_Forming: 
      - Process: "A4_Forming/Process.md"
      - Product: "A4_Forming/Products.md"
  - A5_Result: "A5_Result.md"      
  - About: "about.md"
  - index:
      - scripts: 
          Voxelization: "index/scripts/Voxelize.ipynb"
          Atrium allocation: "index/scripts/atrium allocation and green path finding.ipynb.ipynb"
          Shadow casting analysis: "index/scripts/shadow.ipynb"
          Visibility analysis: "index/scripts/visibility.ipynb"
          Sun access analysis: "index/scripts/sun.ipynb"
          Green access analysis: "index/scripts/green.ipynb"
          Noise analysis: "index/scripts/noise field.ipynb"
          Shafts and shortest paths: "index/scripts/corridors.ipynb"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"

theme:
  name: "material"
  palette:
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

  font:
    text: Roboto

markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji

plugins:
  - mknotebooks